[plugins]
shadow = { id = "com.gradleup.shadow", version = "9.0.0" }
lombok = { id = "io.freefair.lombok", version = "8.14.2" }

[libraries]

## Server Software
paper = { group = "io.papermc.paper", name = "paper-api", version = "1.21.6-R0.1-SNAPSHOT" }
spigot = { group = "org.spigotmc", name = "spigot-api", version = "1.21.6-R0.1-SNAPSHOT" }

velocity = { group = "com.velocitypowered", name = "velocity-api", version = "3.4.0-SNAPSHOT"}
bungee = { group = "net.md-5", name = "bungeecord-api", version = "1.21-R0.3" }

## General
mysql = { group = "mysql", name = "mysql-connector-java", version = "8.0.33"}
hikaricp = { group = "com.zaxxer", name = "HikariCP", version = "5.1.0"}

websocket = { group = "org.java-websocket", name = "Java-WebSocket", version = "1.6.0"}
nettyBuffer = { group = "io.netty", name = "netty-buffer", version = "4.2.4.Final"}

adventureApi = { group = "net.kyori", "name" = "adventure-api", version = "4.24.0"}
miniMessage = { group = "net.kyori", name = "adventure-text-minimessage", version = "4.11.0"}

jetanno = { group = "org.jetbrains", name = "annotations", version = "24.0.1"}

gson = { group = "com.google.code.gson", name = "gson", version = "2.13.1"}
snakeyaml = { group = "org.yaml", name = "snakeyaml", version = "2.2" }
toml4j = { group = "com.moandjiezana.toml", name = "toml4j", version = "0.7.2" }

## Velocity
packeteventsVelocity = { group = "com.github.retrooper", name = "packetevents-velocity", version = "2.9.5"}
viaversionVelocity = { group = "com.viaversion", name = "viaversion-velocity", version = "5.4.2"}

## Bungee
packeteventsBungee = { group = "com.github.retrooper", name = "packetevents-bungeecord", version = "2.9.5"}

## Spigot
packeteventsSpigot = { group = "com.github.retrooper", name = "packetevents-spigot", version = "2.9.5"}

## Internal
common = { group = "net.rubrion.common", name = "api", version = "1.0.1"}

[bundles]
database = ["mysql", "hikaricp"]
config = ["gson", "snakeyaml", "toml4j"]